image: node:9

stages:
  - build
  - binaries
  - test

before_script:
  - yarn config set cache-folder .yarn
  - yarn

build:
  stage: build
  script:
    - yarn run build

binaries:
  stage: binaries
  script:
    - yarn run make:binaries

test:
  stage: test
  script:
    - yarn run test