image:
  - node:9

before_script:
  - yarn config set cache-folder .yarn
  - yarn

build:
  script:
    - yarn run build

binaries:
  script:
    - yarn run make:binaries

test:
  script:
    - yarn run test