# Unprivileged user to run iri with
iri_username: iri

# Base directory where iri is installed and runs from
iri_basedir: /var/lib/iri

# The iri version to install
iri_version: 1.4.1.2

# This is the sha256sum of the iri version noted above. Checksum has to change to match the
# version of the file https://github.com/iotaledger/iri/releases/download/v{version}/iri-{version}.jar
iri_jar_checksum: 'sha256:dda215a1869b23bbe48cbaac7749cefd399c4aeff6493f3b74e1524a4d988d9f'

# The TCP port on which IRI listens for API calls and allows for light wallets to connect to
iri_api_port: 14265

# The UDP neighbor peering port
iri_udp_port: 14600

# The TCP neighbor peering port
iri_tcp_port: 14600

# Limit IRI memory usage
iri_java_mem: 4096m

# Initial memory usage
iri_init_java_mem: 1024m

# Automatically configure memory limits
# Overrides above `iri_java_mem` value
memory_autoset: true

# Exclude from the API the commands below
# works in conjunction with `--remote` / `api_port_remote: true`
iri_remote_limit_api: "removeNeighbors, addNeighbors, interruptAttachingToTangle, attachToTangle, getNeighbors"

# Let the iri_api_port bind to all interfaces (0.0.0.0).
# `true` is necessary in order to allow external wallets/APIs to connect without tunneling.
# If set to `false` it will only bind to localhost (127.0.0.1)
api_port_remote: false
